// ─────────────────────────────────────────────────────────────────
//  Domain Types  (mirrors the mobile app's src/types/index.ts)
// ─────────────────────────────────────────────────────────────────

export interface Coordinates {
  latitude: number;
  longitude: number;
  altitude?: number;
  accuracy?: number;
}

export interface JournalPhoto {
  id: string;
  remoteUrl: string;        // Firebase Storage URL
  tags: string[];           // AI-generated tags
  taggingStatus: 'pending' | 'processing' | 'done' | 'failed';
  order: number;
  createdAt: string;        // ISO8601
}

export type SyncStatus = 'synced' | 'conflict' | 'error';

export interface JournalEntry {
  id: string;               // UUID v4 — generated by mobile client
  userId: string;           // Firebase Auth UID
  title: string;
  description: string;
  photos: JournalPhoto[];
  location?: Coordinates;
  locationName?: string;
  tags: string[];
  createdAt: string;        // ISO8601
  updatedAt: string;        // ISO8601 — used for LWW conflict resolution
  syncStatus: SyncStatus;
  isDeleted: boolean;       // soft-delete — never hard-delete for sync safety
  voiceNoteUrl?: string;
  voiceNoteTranscript?: string;
}

export interface UserProfile {
  id: string;               // Firebase Auth UID
  email: string;
  name: string;
  photoUrl?: string;
  provider: 'google' | 'apple';
  createdAt: string;
  updatedAt: string;
}

// ─── Sync Types ───────────────────────────────────────────────────

export interface SyncRequest {
  lastSyncAt: string;       // ISO8601 — client's last successful sync time
  entries: JournalEntry[];  // locally mutated entries since last sync
}

export interface SyncResponse {
  syncedAt: string;         // server timestamp of this sync
  updatedEntries: JournalEntry[];  // server entries newer than lastSyncAt
  conflicts: ConflictResult[];     // entries where conflict was detected
  deletedIds: string[];            // IDs soft-deleted on server
}

export interface ConflictResult {
  entryId: string;
  winner: 'client' | 'server';
  winningEntry: JournalEntry;
  reason: string;
}

// ─── API Response wrapper ─────────────────────────────────────────

export interface ApiResponse<T = unknown> {
  success: boolean;
  data?: T;
  error?: string;
  message?: string;
}

// ─── Search / Filter ─────────────────────────────────────────────

export interface SearchQuery {
  q?: string;              // full-text on title + description
  tags?: string[];         // filter by tags (AND logic)
  dateFrom?: string;       // ISO8601
  dateTo?: string;         // ISO8601
  lat?: number;            // proximity center
  lng?: number;
  radiusKm?: number;       // default 10
  limit?: number;          // default 20
  cursor?: string;         // Firestore cursor for pagination
}
